### ISSUE TITLE
Android白屏问题

### ISSUE THREAD

**Issue by Jadramcool** [fly-vue3-templates/vue3-uniapp-template#1]
目前测试，是http的问题导致白屏问题
能力有限，还不清楚怎么改

**Comment by Jadramcool** [comment]
![image](https://github.com/fly-vue3-templates/vue3-uniapp-template/assets/62826075/61d30f10-f705-406e-ab72-6e87cb321ab8)
http里面不不能用pinia，为啥，不清楚

**Comment by codercup** [comment]
原来这样，我试试看。

**Comment by codercup** [comment]
感谢感谢，果然是可以的！

**Comment by codercup** [comment]
> 目前测试，是http的问题导致白屏问题 能力有限，还不清楚怎么改

感谢，我已经改好了。

**Comment by Jadramcool** [comment]
感谢提供的这么全面的模板，我照着自己安装了一遍，很牛！

**Comment by codercup** [comment]
> 感谢提供的这么全面的模板，我照着自己安装了一遍，很牛！

多多star哈
